### ISSUE TITLE
Code Review - by Ellie Ringwood

### ISSUE THREAD

**Issue by Ellie-Ringwood** [eirynferguson/OOP#1]
Its unfortunate that I was unable to run your code, but overall the code is easy to read due to many helpful comments.

I have a few inputs about the use of the Card class. It seems that you have only instantiated one Card object in the Pack constructor. It may be easier to have a for loop that creates 52 Card objects, each with their own value and suit variable instead of the arrays you have. This will help with encapsulation to have objects for each card in the pack, with their own attributes and behaviours. 

I am curious about the shuffle methods as I suspect if they were run they would return just one value and not produce a shuffled pack. Take the first (fisher-yates) shuffle, It would pick a random card and return it, instead of shuffling the deck. The fisher-yates is done by going through the deck and putting each card in a random position. For the second (riffle) shuffle, you have picked random values between 0 and 26 and combined them in a string. The riffle shuffle splits the deck into two sides and then 'takes one from one side and one from the other' until they are merged into once deck again.

In the way of error handling, you have taken into consideration if the user enters more than 52 cards which is good. Because the program returns a random card without removing it from the deck means that the same card can be dealt multiple times. Have you considered keeping track of the order of the cards and maybe the number of cards left in the pack so that cards aren't dealt repeatedly.

I noticed that the user would not be able to quit the program as in the testing class you have used a while loop for the running of the code but have put "while(run=true)", this will never end as you need ==. It is an easily overlooked mistake that I make a lot :)

Again well done on your very clear program, I hope this was helpful

**Comment by eirynferguson** [comment]
Thank you for your input! I appreciate it, especially with the few syntax/logic errors.
