### ISSUE TITLE
Code Review - Caitlin Townsend

### ISSUE THREAD

**Issue by CTownsend20** [eirynferguson/OOP#2]
- Your use of comments in your code is very good and make the code easy to follow.
- In your code there are a few cases of missing ; at the end of certain lines, therefore I think it would be beneficial to have another read through it and make sure that there are semicolons used where needed. 
- You have implemented various different successful ways of error handling already and to add to this even more maybe you could consider writing something in the testing class so that if the user inputs a number that isn't 1 - 4, the program will still respond to them and tell them that their input is invalid?
- To improve your code you could implement a way of keeping track of the cards that have already been dealt, so that you wouldn't risk dealing the same card multiple times.
- Overall your code represents a good implementation of object oriented programming.

**Comment by eirynferguson** [comment]
Thank you. I never thought of tracking cards that have been dealt that's a good idea! I appreciate the feedback.
